### PR TITLE
Adjust compatibility and deprecated operators for swift 3 (support for Swift >= 2.2)

### PR DESCRIPTION
**Pull request by AF-cgi**

### CODE REVIEW

**Comment by lwdupont** [comment]
Sorry for the delay, I've started to help out with keeping things up to date here. 

This pull request seems fine, still interested in merging I presume?

**Comment by AF-cgi** [comment]
Yes, I think so.

**Comment by AndreasBoehm** [comment]
Hi @lwdupont,
can we get this merged please? :)

**Review by lwdupont — APPROVED** [review]
Sorry for the delay. Looks great to me.

**Pull request merged**
